server:
  port: 8002
mybatis:
  type-aliases-package: com.he.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

  #spring 的配置

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://parking.guos.com.cn:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Guo7764@9d
