server:
  port: 8002
mybatis:
  type-aliases-package: com.he.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

  #spring 的配置

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
   #url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://parking.guos.com.cn:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Guo7764@9d

#Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-provicer-dept-8002


#info 配置
info:
  app.name: he-springcloud
  company.name: hejinyu110.com