server:
  port: 80

#Eureka
eureka:
  client:
    service-url:
      defautZone: http://localhost:7003/eureka/,http://localhost:7002/eureka/,http://localhost:7001/eureka/
    register-with-eureka: false #客户端不用注册
