server:
  port: 9527


#Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  #      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-zuul-9527
    prefer-ip-address: true

spring:
  application:
    name: springcloud-zuul


info:
  app.name: he-springcloud
  company.name: www.he.com
zuul:
  routes:
    mydept-service-id: springcloud-provider-dept
    mydept-id: /mydept/*
