server:
  port: 9527


#Eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  #      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: springcloud-zuul-9527
    prefer-ip-address: true

spring:
  application:
    name: springcloud-zuul


info:
  app.name: he-springcloud
  company.name: www.he.com
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
#  ignored-services: springcloud-provider-dept  #原服务名称不让访问 隐藏单个
  ignored-services: "*"  #隐藏所有服务
#  prefix: /he  # 统一的服务访问前缀
